project:
  type: website  
  output-dir: _site

website:  
  navbar:
    right:
      - icon: translate
        text: "Idioma"
        menu:
          - text: "Español"
            href: /es/index.qmd
          - text: "English"
            href: /en/index.qmd
      - icon: github
        href: https://github.com/Aderfi