project:
  type: website
  output-dir: _site

website:
  title: Adrim Portfolio
  favicon: media/logo.png
  description: "Pharmacist & Bioinformatics Researcher | AI in Precision Medicine"
  site-url: "https://Aderfi.github.io"

  navbar:
    search: true
    logo: media/logo.png
    left:
      - text: "Inicio"
        href: es/index.qmd
      - text: "Proyectos"
        menu:
          - text: "Pharmagen"
            href: es/proyectos/pharmagen.qmd
      - text: "Blog"
        href: es/blog/index.qmd

    right:
      - icon: translate
        text: "Idioma"
        menu:
          - text: "Español"
            href: es/index.qmd
          - text: "English"
            href: en/index.qmd
      - icon: github
        href: https://github.com/Aderfi
      - icon: linkedin
        href: https://linkedin.com/in/adrim-hamed-outmani-047491290

  page-footer:
    left: "© 2026 Adrim Hamed Outmani"
    right:
      - icon: code-slash
        text: "Desarrollado en Debian 13 con Quarto"

format:
  html:
    theme:
      light: [cosmo, styles.css, colors.css]
      dark: [darkly, styles.css, colors-dark.css]
    theme-default: dark
    toc-title: "Contenido"
    code-fold: true
    code-copy: true
    code-summary: "Ver código"
    mainfont: Inter
    highlight-style: media/themes/onedark.theme
    number-sections: false
    lang: es-ES

execute:
  freeze: auto
  echo: true
